### ISSUE TITLE
Duplicate token security vulnerability

### ISSUE THREAD

**Issue by musnit** [cosmos/gravity#181]
With the change to remove whitelisting, the bridge is now vulnerable to an attacker who can duplicate tokens:

An attacker can duplicate any ERC20 that has come across the bridge by creating a copy of that ERC20's contract on Ethereum and relaying over copied tokens. The copied tokens will be indistinguishable from originals on the Cosmos side due to this security vulnerability.

**Comment by musnit** [comment]
@okwme cosmos doesn't support long enough names to do this

**Comment by okwme** [comment]
I see your comment here discussing this: https://github.com/cosmos/peggy/issues/123#issuecomment-612855798

**Comment by jkbrooks** [comment]
@okwme Is this still an open now that #123 has been closed?

**Comment by musnit** [comment]
@jkbrooks still an issue. to resolve, would need to implement a custom token metadata module, either within the peggy codebase or for cosmos-sdk as a whole
